### ISSUE TITLE
Enemies stay dead after they are killed.

### ISSUE THREAD

**Issue by arimaeda** [arimaeda/TheMiniRPG#1]
An enemy retains its HP value following the end of combat.

Solutions:
- Set enemy.HP = enemy.HPMax at the end of every battle exit, including running away and death.
- Make each fight against an *instance* of the enemy. *preferred solution*

**Comment by stuffgal** [comment]
This is a problem because enemies aren't made into separate instances. I will work on the Enemy module now so that it will generate a new enemy instance by taking in a random number! <3

**Comment by arimaeda** [comment]
Enemies are now instanced, and the issue is resolved.
